# -*- coding: utf-8 -*-
"""helpy chat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFGQOIUsJqQ5k7DOtXvhm0r7CmxldoD6
"""

#의도대로. 성공.

import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import datetime

# Load the model
model = SentenceTransformer('jhgan/ko-sroberta-multitask')

# Load and preprocess the dataframe
df = pd.read_csv('helpy 발화 - 시트1.csv')
df = df[~df['챗봇 발화'].isna()]
df['embedding'] = df['사용자 발화'].map(lambda x: list(model.encode(x)))

# Continuous chatbot loop
while True:
    text = input("당신: ")

    if text.lower() == '잘있어' or text.lower() == 'break': # Added termination condition
        print('Helpy: 안녕히 가세요!')
        break
    elif '시간' in text:
        print(f"Helpy: 현재 시간은 {datetime.datetime.now().strftime('%H:%M')}예요!")
    else:
        embedding = model.encode(text)
        df['distance'] = df['embedding'].map(lambda x: cosine_similarity([embedding], [x]).squeeze())
        answer = df.loc[df['distance'].idxmax()]

        # Add a similarity threshold as per the task requirements
        similarity_threshold = 0.6 # This threshold can be adjusted
        if answer['distance'] >= similarity_threshold:
            print('Helpy:', answer['챗봇 발화'])
            print('유사도', answer['distance'])
        else:
            print('Helpy: 모르겠어요, 아직 학습되지 않았나봐요.')